#!/usr/bin/env bash
# Commits a refreshed trending.json straight to main, when it changed.
#
# A commit, where its companion opens a pull request, and the difference is deliberate.
# The six blogs below are an editorial recommendation: someone chose them, and
# docs/plans/popular-blogs-landing-plan.md keeps that choice in review. These four are a
# data feed - whatever Hacker News read this week, filtered by rules already written
# down - so there is no judgement for a reviewer to apply. A daily pull request nobody
# can meaningfully reject is the "rubber-stamped PR" that
# docs/plans/keeping-the-curated-lists-current.md argues against: it removes the check
# while keeping the ceremony.
#
# What stands in for review is the gates. build_trending.py refuses to write unless every
# row is a blog-kinded, non-denied, usably-named host that is not already in the six,
# and whose post is in the index. It cannot ship a short section or an empty one.
#
# Run by .github/workflows/refresh-trending.yml, which supplies the token and holds
# `contents: write`.

set -euo pipefail

LIST="${LIST:-web/src/lib/data/trending.json}"
BRANCH="${BRANCH:-main}"

log() { printf '\n\033[36m==> %s\033[0m\n' "$1"; }
# Actions renders this under the run; a local run just prints.
summary() {
	if [[ -n "${GITHUB_STEP_SUMMARY:-}" ]]; then
		cat >>"$GITHUB_STEP_SUMMARY"
	else
		cat
	fi
}

cd "$(dirname "${BASH_SOURCE[0]}")/../.."

# Staged before it is compared. `git diff` on its own is blind to a file git does not
# yet track, so on the run that first creates this list - or on one that restores it
# after a deletion - it would report "unchanged" and quietly commit nothing.
git add "$LIST"
if git diff --cached --quiet -- "$LIST"; then
	log "The same four posts as yesterday, so nothing is committed"
	echo 'Trending posts unchanged. Nothing committed.' | summary
	exit 0
fi

log "Committing $LIST"
git config user.name 'github-actions[bot]'
git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
git commit -m "chore(trending): refresh what the corpus is being read for ($(date -u +%Y-%m-%d))" \
	-m 'Generated by .github/workflows/refresh-trending.yml from the Hacker News API.'

# Rebased rather than forced: main moves on its own, and a day's four posts are never
# worth overwriting whatever landed while this ran.
git pull --rebase --autostash origin "$BRANCH"
git push origin "HEAD:$BRANCH"

{
	echo '### Trending posts refreshed'
	echo
	git show --no-patch --format='%s' HEAD
	echo
	echo '```'
	git show --stat --format='' HEAD
	echo '```'
} | summary
