#!/usr/bin/env bash
# Proposes a refreshed popular.json as a pull request, and closes the previous one.
#
# A pull request rather than a push to main because the landing page is an editorial
# surface: docs/plans/popular-blogs-landing-plan.md keeps the list in Git so a change to
# what the front page recommends goes through review. Automating the generation does not
# change who approves it.
#
# At most one is ever open. Two refreshes proposing different lists against the same main
# is a conflict in a generated file, which is work nobody should do by hand, so each run
# supersedes the last.
#
# Run by .github/workflows/refresh-popular.yml, which supplies GH_TOKEN and holds
# `contents: write` and `pull-requests: write`.

set -euo pipefail

BRANCH="${BRANCH:?the branch to propose from is required}"
REPORT="${REPORT:?the report written by refresh-popular.sh is required}"
LIST="${LIST:-web/src/lib/data/popular.json}"
# Every branch this script has ever opened from. Used to find the previous pull request,
# rather than a label, which would have to exist in the repository first.
BRANCH_PREFIX="${BRANCH_PREFIX:-bot/popular-}"
# Linked at the foot of the body. Empty when run outside Actions.
RUN_URL="${RUN_URL:-}"

log() { printf '\n\033[36m==> %s\033[0m\n' "$1"; }
die() { printf '\033[31merror: %s\033[0m\n' "$1" >&2; exit 1; }
# Actions renders this under the run; a local run just prints.
summary() {
	if [[ -n "${GITHUB_STEP_SUMMARY:-}" ]]; then
		cat >>"$GITHUB_STEP_SUMMARY"
	else
		cat
	fi
}

cd "$(dirname "${BASH_SOURCE[0]}")/../.."

[[ "$BRANCH" == "$BRANCH_PREFIX"* ]] || die "BRANCH must start with $BRANCH_PREFIX"
[[ -f "$REPORT" ]] || die "$REPORT not found; did refresh-popular.sh run?"

if git diff --quiet -- "$LIST"; then
	log "The list is unchanged, so there is nothing to propose"
	echo 'The list is unchanged. Nothing to open.' | summary
	exit 0
fi

# Read before the new one exists, and excluding this run's own branch: a re-run reuses
# the run number, and would otherwise close the pull request it is about to reuse.
log "Previous refreshes still open"
superseded="$(gh pr list --state open --json number,headRefName \
	--jq ".[] | select(.headRefName | startswith(\"$BRANCH_PREFIX\"))
	          | select(.headRefName != \"$BRANCH\") | .number")"
echo "  ${superseded:-none}"

# Read once, so the commit and the title cannot straddle midnight.
title="chore(popular): refresh widely shared blogs ($(date -u +%Y-%m-%d))"

log "Pushing $BRANCH"
git config user.name 'github-actions[bot]'
git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
# -C, not -c: a local re-run should reset the branch rather than refuse to start.
git switch -C "$BRANCH"
git add "$LIST"
git commit -m "$title" \
	-m 'Generated by .github/workflows/refresh-popular.yml from popularity.json.'
# Forced, so re-running a run that failed after pushing proposes this attempt's list
# rather than the one that failed.
git push --force origin "$BRANCH"

body="$(mktemp)"
trap 'rm -f "$body"' EXIT
{
	# A marker, so anything that later needs to recognise these does not have to guess
	# from the title.
	echo '<!-- popular-blogs-refresh -->'
	echo
	cat "$REPORT"
	# Not `[[ ... ]] && printf`: as the last command in the group that returns 1 when
	# RUN_URL is empty, and `set -e` would end the script on it.
	if [[ -n "$RUN_URL" ]]; then
		printf '\n[Workflow run](%s)\n' "$RUN_URL"
	fi
} >"$body"

# Opened before the last one is closed, so there is never a moment with no refresh in
# review and the closing note can point forward to this one. `gh pr create` fails on a
# branch that already has one, which a re-run does, so that is an edit instead.
log "Pull request"
# Only an OPEN one is reused. A closed pull request on this branch - someone rejected
# the last attempt, then the run was retried - must become a new one, not a silent edit
# to something nobody is looking at.
url="$(gh pr view "$BRANCH" --json url,state \
	--jq 'select(.state == "OPEN") | .url' 2>/dev/null || true)"
if [[ -n "$url" ]]; then
	gh pr edit "$url" --body-file "$body"
	echo "  updated $url"
else
	url="$(gh pr create --base main --head "$BRANCH" --title "$title" --body-file "$body")"
	echo "  opened $url"
fi

# Superseded, not rejected: whatever it proposed, this one proposes against fresher
# standing. Its branch goes with it, so the prefix search stays short.
for number in $superseded; do
	gh pr close "$number" --delete-branch \
		--comment "Superseded by $url, built from a newer \`popularity.json\`."
	echo "  closed #$number"
done

echo "[$url]($url)" | summary
