"""Tests for the four posts at the top of the landing page.

Stdlib unittest and no network, so it runs anywhere the extractor's venv does:

    cd sources/tools && .venv/bin/python -m unittest test_build_trending -v

The refusal tests carry the weight. This job commits to main unreviewed, so a check that
degrades instead of stopping puts a broken section above the fold and nobody sees the
warning it printed.
"""

from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

import build_trending
from build_trending import Refused, article_id, candidates, choose, shown_below


def source(site, name="A Blog", kind=("personal-blogs",), id=None):
    return {
        "id": id if id is not None else site.split("//")[-1].strip("/").replace(".", "-"),
        "site": site,
        "name": name,
        "kind": list(kind),
    }


def hit(url, points=100):
    return {"url": url, "points": points, "title": "As Hacker News has it"}


class ArticleID(unittest.TestCase):
    """The key the vouch looks up. It has one job: agree with Go."""

    def test_mirrors_the_crawler(self):
        # articleID in api/internal/discovery/crawl.go is
        #   sanitizeKey(sourceID) + "-" + hex(sha256(url)[:8])
        # Cross-checked against production: these ids found 8 real documents in the live
        # index when the window was measured, which no amount of local pinning would show.
        self.assertEqual(
            article_id("simonwillison", "https://example.com/post"),
            "simonwillison-061128ccde4ce470",
        )

    def test_sanitises_the_source_id_the_way_go_does(self):
        # Azure AI Search keys allow only letters, digits, underscore, dash and equals.
        self.assertEqual(
            article_id("a.b c/d", "https://example.com/post"),
            "a-b-c-d-061128ccde4ce470",
        )

    def test_a_different_url_is_a_different_key(self):
        a = article_id("blog", "https://example.com/post")
        b = article_id("blog", "https://example.com/post/")
        self.assertNotEqual(a, b)

    def test_it_agrees_with_go_on_the_awkward_cases(self):
        """Generated by running the real sanitizeKey/articleID from crawl.go.

        The two that could plausibly have diverged: Go writes one '-' per non-matching
        *rune*, not per byte, so an accented character collapses to one dash and not
        two; and a non-ASCII URL is hashed as UTF-8 on both sides.
        """
        self.assertEqual(
            article_id("caf" + chr(233) + "-blog", "https://example.com/caf" + chr(233)),
            "caf--blog-b65dae36fa32fd0d",
        )
        self.assertEqual(
            article_id("blog", "https://" + chr(20363) + ".example/" + chr(25991) + chr(31456)),
            "blog-668900f1b6edffbd",
        )
        self.assertEqual(article_id("", ""), "-e3b0c44298fc1c14")
        self.assertEqual(article_id("UPPER_case-9", "http://x"), "UPPER_case-9-037ab55168fe8769")


class Candidates(unittest.TestCase):
    def test_a_trending_blog_is_a_candidate(self):
        got = candidates([source("https://antirez.com/", "antirez")],
                         [hit("https://antirez.com/news/1")], set())

        self.assertEqual([r["host"] for r in got], ["antirez.com"])
        self.assertEqual(got[0]["url"], "https://antirez.com/news/1")

    def test_a_trending_newspaper_is_not(self):
        # The same one-line newspaper filter the six use: no kind, not a blog.
        got = candidates([source("https://bbc.com/", "BBC News", kind=())],
                         [hit("https://bbc.com/news/1")], set())

        self.assertEqual(got, [])

    def test_a_denied_host_is_not(self):
        got = candidates([source("https://github.com/", "GitHub")],
                         [hit("https://github.com/x/y")], set())

        self.assertEqual(got, [])

    def test_a_blog_with_an_unusable_name_is_not(self):
        # It would be refused by the list below, so it cannot appear above it.
        got = candidates([source("https://gwern.net/", "Essays")],
                         [hit("https://gwern.net/essay")], set())

        self.assertEqual(got, [])

    def test_a_blog_already_in_the_six_is_not(self):
        # The same name twice on one screen reads as a bug.
        got = candidates([source("https://simonwillison.net/", "Simon Willison")],
                         [hit("https://simonwillison.net/p")], {"simonwillison.net"})

        self.assertEqual(got, [])

    def test_a_blog_not_in_the_corpus_is_not(self):
        got = candidates([source("https://antirez.com/", "antirez")],
                         [hit("https://stranger.example/post")], set())

        self.assertEqual(got, [])

    def test_one_row_per_blog_taking_its_best_story(self):
        # danluu.com trended twice in the measured week; the section has one row for it.
        got = candidates(
            [source("https://danluu.com/", "danluu")],
            [hit("https://danluu.com/big", 863), hit("https://danluu.com/small", 404)],
            set(),
        )

        self.assertEqual(len(got), 1)
        self.assertEqual(got[0]["url"], "https://danluu.com/big")

    def test_a_story_with_no_url_is_skipped(self):
        # An Ask HN post has no url at all.
        got = candidates([source("https://antirez.com/", "antirez")],
                         [{"points": 900, "title": "Ask HN: anything"}], set())

        self.assertEqual(got, [])


class Choosing(unittest.TestCase):
    def rows(self, count):
        return [
            {"name": f"Blog {i}", "host": f"b{i}.example", "ids": [f"b{i}"],
             "url": f"https://b{i}.example/post", "points": 1000 - i}
            for i in range(count)
        ]

    def test_without_a_key_nothing_can_be_vouched_for(self):
        with self.assertRaises(Refused):
            choose(self.rows(10), 2, endpoint="", key="")

    def test_it_walks_past_posts_the_crawler_never_reached(self):
        # Measured at 8 in 14, so walking is the normal case rather than the exception.
        found = {"b2.example", "b3.example"}
        with patch.object(build_trending, "indexed_article",
                          lambda e, k, row: {"title": "In the index"}
                          if row["host"] in found else None):
            got = choose(self.rows(10), 2, endpoint="https://x", key="k")

        self.assertEqual([r["host"] for r in got], ["b2.example", "b3.example"])

    def test_it_prints_the_title_the_blog_used(self):
        # Hacker News titles are edited by moderators; the feed's is what the blog said.
        with patch.object(build_trending, "indexed_article",
                          lambda e, k, row: {"title": "Hang on to your Firefox!"}):
            got = choose(self.rows(4), 1, endpoint="https://x", key="k")

        self.assertEqual(got[0]["title"], "Hang on to your Firefox!")

    def test_an_untitled_document_is_skipped(self):
        # A feed entry with no title at all indexes as a document with none, and would
        # render as an empty link. One fewer row is the better failure.
        with patch.object(build_trending, "indexed_article",
                          lambda e, k, row: {"title": "   "}
                          if row["host"] == "b0.example" else {"title": "Real"}):
            got = choose(self.rows(4), 1, endpoint="https://x", key="k")

        self.assertEqual(got[0]["host"], "b1.example")

    def test_a_short_section_is_refused_rather_than_shipped(self):
        with patch.object(build_trending, "indexed_article", lambda e, k, row: None):
            with self.assertRaises(Refused):
                choose(self.rows(10), 4, endpoint="https://x", key="k")

    def test_it_stops_rather_than_asking_about_everything(self):
        asked = []
        with patch.object(build_trending, "indexed_article",
                          lambda e, k, row: asked.append(row) or None):
            with self.assertRaises(Refused):
                choose(self.rows(500), 4, endpoint="https://x", key="k")

        self.assertEqual(len(asked), build_trending.MAX_SCAN)


class Window(unittest.TestCase):
    """One request, and the shapes a bad answer takes."""

    def answer(self, hits):
        class Response:
            def read(inner):
                return json.dumps({"hits": hits}).encode()

            def __enter__(inner):
                return inner

            def __exit__(inner, *a):
                return False
        return Response()

    def test_a_normal_week_is_sorted_by_points(self):
        hits = [hit("https://a.example/1", 10), hit("https://b.example/2", 900)]
        hits += [hit(f"https://c{i}.example/", i) for i in range(build_trending.MIN_STORIES)]
        with patch.object(build_trending, "urlopen", lambda *a, **k: self.answer(hits)):
            got = build_trending.stories(7, 50)

        self.assertEqual(got[0]["points"], 900)

    def test_an_answer_that_is_not_a_list_is_refused(self):
        # Sorting over a dict would iterate its keys and fail on .get with a traceback
        # rather than a message, which is the wrong way for a scheduled job to end.
        with patch.object(build_trending, "urlopen",
                          lambda *a, **k: self.answer({"unexpected": True})):
            with self.assertRaises(Refused):
                build_trending.stories(7, 50)

    def test_a_truncated_window_is_refused(self):
        # "Nothing was popular" and "the API was down" produce the same empty section,
        # so a thin answer is treated as the second.
        with patch.object(build_trending, "urlopen", lambda *a, **k: self.answer([])):
            with self.assertRaises(Refused):
                build_trending.stories(7, 50)


class ShownBelow(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)

    def test_it_reads_the_hosts_the_six_offer(self):
        path = Path(self.tmp.name) / "popular.json"
        path.write_text(json.dumps({"corpus": 1, "blogs": [
            {"name": "antirez", "site": "https://antirez.com/", "host": "antirez.com",
             "ids": ["antirez"]},
        ]}), encoding="utf-8")

        self.assertEqual(shown_below(path), {"antirez.com"})

    def test_a_missing_list_excludes_nothing(self):
        self.assertEqual(shown_below(Path(self.tmp.name) / "absent.json"), set())

    def test_a_malformed_list_excludes_nothing(self):
        path = Path(self.tmp.name) / "popular.json"
        path.write_text("[]", encoding="utf-8")

        self.assertEqual(shown_below(path), set())


if __name__ == "__main__":
    unittest.main()
