"""Turning checked candidates into blogs.yml and the audit CSV."""

from __future__ import annotations

import csv
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

import yaml

from .models import Candidate, Committed
from .tags import ordered_tags, split_provenance, tagify
from .urls import MULTI_TENANT_HOST_SUFFIXES, domain_name, site_key

YAML_HEADER = """# Approved sources. Changes go through normal Git review — see docs/system-design.md.
#
#   id    stable identifier, used in article IDs and logs
#   name  human-readable title
#   site  homepage
#   feed  RSS/Atom feed, if the site publishes one
#   kind  what sort of blog it is, e.g. personal-blogs, company-blogs
#   tags  subject tags, lowercase kebab-case
#
# Generated by sources/tools/build_sources.py; every site below answered an HTTP
# request at generation time.
"""

AUDIT_COLUMNS = ["site", "reachable", "status_code",
                 "error", "feed", "name", "tags", "origins"]


class BlogsDumper(yaml.SafeDumper):
    """Indent sequences under their key, matching the hand-written blogs.yml."""

    def increase_indent(self, flow: bool = False, indentless: bool = False):  # noqa: ARG002
        return super().increase_indent(flow, False)


class FlowList(list):
    """A list rendered inline, e.g. tags: [tech, rust]."""


BlogsDumper.add_representer(
    FlowList,
    lambda dumper, data: dumper.represent_sequence(
        "tag:yaml.org,2002:seq", data, flow_style=True),
)


def source_id(site: str, used: set[str]) -> str:
    """A short stable id from the host, e.g. https://eng.uber.com/ -> eng-uber."""
    parsed = urlparse(site)
    host = (parsed.hostname or "").lower().removeprefix("www.")
    labels = host.split(".")

    if host.endswith(MULTI_TENANT_HOST_SUFFIXES) and len(labels) > 2:
        parts = labels[:1]
    elif len(labels) > 1:
        parts = labels[:-1]
    else:
        parts = labels

    segments = [s for s in parsed.path.split("/") if s]
    if segments:
        parts = [*parts, segments[0].lstrip("@~")]

    base = tagify("-".join(parts)) or "source"
    candidate = base
    n = 2
    while candidate in used:
        candidate = f"{base}-{n}"
        n += 1
    used.add(candidate)
    return candidate


def committed_sources(path: Path) -> Committed:
    """What the last generated list already knew, so a rebuild can carry it forward.

    Ids matter because an article's id is derived from its source's, so reassigning
    one strands every article already stored for that blog. Feeds matter because a
    build that fails to confirm one would otherwise record its absence, which moves
    the blog onto the slower sitemap path and off the crawler altogether when it has
    no sitemap.
    """
    if not path.exists():
        return Committed()

    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    entries = [e for e in (data.get("sources") or []) if e.get("site")]

    return Committed(
        ids={e["site"]: e["id"] for e in entries if e.get("id")},
        feeds={site_key(e["site"]): e["feed"] for e in entries if e.get("feed")},
    )


def build_entries(checked: list[Candidate], known: dict[str, str] | None = None) -> list[dict[str, Any]]:
    """One entry per site, sorted by name. Redirects can land several candidates on one blog."""
    by_site: dict[str, Candidate] = {}
    for candidate in checked:
        existing = by_site.get(candidate.site)
        if not existing:
            by_site[candidate.site] = candidate
            continue
        existing.tags.update(candidate.tags)
        existing.fallback_tags.update(candidate.fallback_tags)
        existing.origins.update(candidate.origins)
        if not existing.feed and candidate.feed:
            existing.feed = candidate.feed

    ordered = sorted(by_site.values(), key=lambda c: (
        (c.name or "").lower(), c.site))

    # An article's id is derived from its source id, so reassigning one strands every
    # article already stored for that blog. Sites that were in the last list keep their
    # id, and every id the last list handed out is reserved before any new site may
    # generate one. Reserving all of them, not just the ones seen again in this run,
    # is what stops a site that was briefly unreachable from losing its id to a
    # newcomer and coming back as a stranger.
    known = known or {}
    pinned = {c.site: known[c.site] for c in ordered if c.site in known}
    used_ids: set[str] = set(known.values())

    entries: list[dict[str, Any]] = []
    for candidate in ordered:
        entry: dict[str, Any] = {
            "id": pinned.get(candidate.site) or source_id(candidate.site, used_ids),
            "name": candidate.name or domain_name(candidate.site),
            "site": candidate.site,
        }
        if candidate.feed:
            entry["feed"] = candidate.feed
        kind, subjects = split_provenance(candidate.tags)
        if kind:
            entry["kind"] = FlowList(kind)
        entry["tags"] = FlowList(ordered_tags(subjects))
        entries.append(entry)

    return entries


def validate_entries(entries: list[dict[str, Any]]) -> None:
    """Fail loudly rather than write a broken source list."""
    seen_ids: set[str] = set()
    seen_sites: set[str] = set()

    for idx, entry in enumerate(entries):
        for key in ("id", "name", "site", "tags"):
            if not entry.get(key):
                raise ValueError(f"sources[{idx}] missing {key}")

        entry_id = entry["id"]
        if entry_id in seen_ids:
            raise ValueError(f"duplicate id in output: {entry_id}")
        if entry_id != tagify(entry_id):
            raise ValueError(f"invalid id convention: {entry_id}")
        seen_ids.add(entry_id)

        site = entry["site"]
        if site in seen_sites:
            raise ValueError(f"duplicate site in output: {site}")
        seen_sites.add(site)

        for url in (site, entry.get("feed")):
            if not url:
                continue
            parsed = urlparse(url)
            if parsed.scheme not in {"http", "https"} or not parsed.netloc:
                raise ValueError(f"invalid URL: {url}")

        for tag in [*entry["tags"], *entry.get("kind", [])]:
            if tag != tagify(tag):
                raise ValueError(f"invalid tag convention: {tag}")


def write_sources_yaml(path: Path, entries: list[dict[str, Any]]) -> None:
    body = yaml.dump(
        {"sources": entries},
        Dumper=BlogsDumper,
        sort_keys=False,
        allow_unicode=True,
        width=200,
    )
    path.write_text(YAML_HEADER + body, encoding="utf-8")


def write_audit_csv(path: Path, candidates: dict[str, Candidate], checked_keys: set[str]) -> None:
    """Every discovered link, whether it made the list or not."""
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=AUDIT_COLUMNS)
        writer.writeheader()
        for key, candidate in candidates.items():
            if key not in checked_keys:
                reachable = "unchecked"
            else:
                reachable = "yes" if candidate.reachable else "no"
            writer.writerow({
                "site": candidate.site,
                "reachable": reachable,
                "status_code": candidate.status_code or "",
                "error": candidate.error or "",
                "feed": candidate.feed or "",
                "name": candidate.name or "",
                "tags": ",".join(ordered_tags(candidate.tags)),
                "origins": " | ".join(sorted(candidate.origins)),
            })
